import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Blob from "@/components/Blob";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Snehdeep Dupare Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-deepblue text-white scrollbar-thin scrollbar-thumb-gray-500 scrollbar-track-transparent hover:scrollbar-thumb-gray-300 scrollbar-thumb-rounded-full`}
      >
        <Header />
        <Blob />
        {children}
      </body>
    </html>
  );
}
